[workspace]
resolver = "3"
members = [
    "core",
    "server",
    "client",
    "examples/mcp-filesystem-client",
    "examples/mcp-filesystem-server",
    "examples/http-client",
    "examples/http-server",
]
