[package]
name = "mcp-filesystem-client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
mcp_client = { path = "../../client" }
mcp_core = { path = "../../core" }
serde_json = "1.0"
