[package]
name = "mcp_examples"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "filesystem"
path = "src/bin/filesystem.rs"

[dependencies]
mcp_client = { path = "../client" }
mcp_core = { path = "../core" }
serde_json = "1.0"
